// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Fri Feb 14 2025 19:09:40 GMT+0200 (Eastern European Standard Time)",
    message: null,
    git: {
        user: "Ignat Krushev",
        branch: "main",
        hash: "580e65",
        fullHash: "580e65684f20d29e0bfab0a05e161efb3a09cd67"
    }
};

export default build;