spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rent' #?currentSchema=rent'
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2dll:
          create_namespaces: true