### POST login (Set access_token to the global variables)
POST {{host}}/api/v0.0.1/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}


###  AddressController # create
POST {{host}}/api/v0.0.1/addresses
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "address": "Бело поле, ул. Струма 38",
  "addressLat": "Belo pole, Struma 38 str.",
  "addressType": "00102",
  "enabled": true,
  "settlement": "04279"
}


###  AddressController # update
PUT {{host}}/api/v0.0.1/addresses/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "id": "9ff16ed3-ac7d-43b7-95e2-5a98e20e5521",
  "address": "Бело поле, ул. Струма 38",
  "addressLat": "Belo pole, Struma 38 str.",
  "addressType": "00102",
  "enabled": true,
  "settlement": "04279"
}


###  AddressController # findById
GET {{host}}/api/v0.0.1/addresses/1
accept: */*
Authorization: Bearer {{access_token}}


###  AddressController # search
GET {{host}}/api/v0.0.1/addresses/search?q=
Content-Type: application/json
Authorization: Bearer {{access_token}}


###  AddressController # history
GET {{host}}/api/v0.0.1/addresses/1/history
accept: */*
Authorization: Bearer {{access_token}}