### POST login (Set access_token to the global variables)
POST {{host}}/api/v0.0.1/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}

###  ClassifierController # findByCode
GET {{host}}/api/v0.0.1/classifiers/0013000/sub-classifiers
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  ClassifierController # findByCode
GET {{host}}/api/v0.0.1/classifiers/0013000/sub-classifiers?grouped=STUDENT
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  ClassifierController # findByCode
GET {{host}}/api/v0.0.1/classifiers/0013000/sub-classifiers?filtered=STUDENT
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  ClassifierController # findByCode
GET {{host}}/api/v0.0.1/classifiers/0013000/sub-classifiers?grouped=UNEMPLOYED&filtered=XXX
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  ClassifierController # findByCode
GET {{host}}/api/v0.0.1/classifiers/0013000
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ClassifierController # findByCode
GET {{host}}/api/v0.0.1/classifiers/0020000
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ClassifierController # searchByParentCode
GET {{host}}/api/v0.0.1/classifiers/search?parentCode=0005000&param=Зам. изпълн
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ClassifierController # findAllParentsClassifierVO
GET {{host}}/api/v0.0.1/classifiers
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ClassifierController # findAllParents
GET {{host}}/api/v0.0.1/classifiers/
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  ClassifierController # createNext
POST {{host}}/api/v0.0.1/classifiers/create-next
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: en

{
  "name": "00001000-en",
  "description": "The code should be 00100 if nomenclature table is empty"
}

###  ClassifierController # createNext
POST {{host}}/api/v0.0.1/classifiers/create-next
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "name": "00001000-bg",
  "description": "Кодът би следвало да е 00001000, ако таблицата с номенклатуре е празна"
}

###  ClassifierController # addNext
POST {{host}}/api/v0.0.1/classifiers/00001000/add-next
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "code": "00001000",
  "name": "00001000-bg",
  "description": "Добавя номенклатура с код 00001000 за език bg"
}

###  ClassifierController # createNext
POST {{host}}/api/v0.0.1/classifiers/0001003/create-next
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: en

{
  "name": "0001000-en",
  "description": "The code should be 00102"
}

###  ClassifierController # addNext
POST {{host}}/api/v0.0.1/classifiers/00001001/add-next
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "code": "00001001",
  "name": "00001001-bg",
  "description": "Добавя номенклатура с код 00101 за език bg"
}

###  ClassifierController # createNext
POST {{host}}/api/v0.0.1/classifiers/00001001/create-next
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "name": "00001001-1",
  "description": "Кода би следвало да е 00001002"
}

###  ClassifierController # createNext
POST {{host}}/api/v0.0.1/classifiers/create-next
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Зодия",
  "description": "Всички зодии по дати",
  "subNomenclatures": [
    {
      "name": "Овен",
      "description": "са хората родени между дати 21 март и 20 Април"
    },
    {
      "name": "Телец",
      "description": "са хората родени между дати 21 април и 20 май"
    },
    {
      "name": "Близнаци",
      "description": "са хората родени между дати 21 май и 20 юни"
    },
    {
      "name": "Рак",
      "description": "са хората родени между дати 21 юни и 21 юли"
    },
    {
      "name": "Лъв",
      "description": "са хората родени между дати 22 юли и 22 август"
    },
    {
      "name": "Дева",
      "description": "са хората родени между дати 23 август и 22 септември"
    },
    {
      "name": "Везни",
      "description": "са хората родени между дати 23 септември и 22 октомври"
    },
    {
      "name": "Скорпион",
      "description": "са хората родени между дати 23 октомври и 21 ноември"
    },
    {
      "name": "Стрелец",
      "description": "са хората родени между дати 22 ноември и 21 декември"
    },
    {
      "name": "Козирог",
      "description": "са хората родени между дати 22 декември и 19 януари"
    },
    {
      "name": "Водолей",
      "description": "са хората родени между дати 20 януари и 18 февруари"
    },
    {
      "name": "Риби",
      "description": "са хората родени между дати 19 февруари и 20 март"
    }
  ]
}

###  ClassifierController # update
PUT {{host}}/api/v0.0.1/classifiers/00001000
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: en

{
  "name": "XXX ZZZ",
  "description": "XXX XXX ZZZ"
}