### POST login (Set access_token to the global variables)
POST {{host}}/api/v0.0.1/auth/signin
Content-Type: application/x-www-form-urlencoded

username=user22&password=string

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}


###  ContractorController # signup
POST {{host}}/api/v0.0.1/auth/signup
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "matchingPassword": "string",
  "email": "krushev@atechtrade.org",
  "fullName": "User 22",
  "username": "user22",
  "password": "string",
  "identifier":"9999"
}


###  ContractorController # signout
POST {{host}}/api/v0.0.1/contractors/signout
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
"id": "f8c2fb51-ac9c-42fe-bf55-69b19b14e770"
}


###  ContractorController # findAll
GET {{host}}/api/v0.0.1/contractors/
accept: */*
Authorization: Bearer {{access_token}}


###  ContractorController # get
GET {{host}}/api/v0.0.1/contractors/username/admin
accept: */*
Authorization: Bearer {{access_token}}


###  ContractorController # getCurrentUser
GET {{host}}/api/v0.0.1/contractors/me
accept: */*
Authorization: Bearer {{access_token}}


###  ContractorController # findById
GET {{host}}/api/v0.0.1/contractors/e9af2ee3-8efb-4ae2-8d89-322b3527966d
accept: */*
Authorization: Bearer {{access_token}}


###  ContractorController # search
GET {{host}}/api/v0.0.1/contractors?q=us
Content-Type: application/json
Authorization: Bearer {{access_token}}


###  ContractorController # history
GET {{host}}/api/v0.0.1/contractors/f1157c95-ea2b-4f04-b67b-7021b862cd34/history
accept: */*
Authorization: Bearer {{access_token}}


###  ContractorController # update
PUT {{host}}/api/v0.0.1/contractors/56ae8613-086a-48bf-ab91-ca6956f6046c
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "id": "56ae8613-086a-48bf-ab91-ca6956f6046c",
  "fullName": "Владимир Ангелов",
  "identifier" : "9503190000",
  "enabled": true,
  "roles": [
      "ADMIN"
  ],
  "facilities" : [
    {
      "email" : "vladimir.angelov@bul-si.bg",
      "phone1" : "0088991122",
      "address" : {
        "id": "ad6ba633-3a61-439f-b614-d8a0107b2417",
        "address": "Бело поле, ул. Струма 38",
        "addressLat": "Belo pole, Struma 38 str.",
        "enabled": true
      }
    }
  ],
  "relatedActivityCategories" : ["00802", "00804"],
  "groups" : [
    "6edfbd80-4fe2-4c45-b308-83b5d5b95a37"
  ],
  "registerCode" : "0002001"
}

###  ContractorController # setEnabled
PUT {{host}}/api/v0.0.1/contractors/9adb2462-4fb0-4d2f-a1c2-765d2ac56f10/true
Content-Type: application/json
Authorization: Bearer {{access_token}}


###  ContractorController # updateRoles
PUT {{host}}/api/v0.0.1/contractors/083a3c6c-235b-4667-81ac-0a64f9eb6147/roles
Content-Type: application/json
Authorization: Bearer {{access_token}}

  ["ADMIN"]


###  AuthController # registerContractorConfirm
PUT {{host}}/api/v0.0.1/auth/signup-confirm
Content-Type: application/json

{
  "token": "cbee37e2-ad96-41ca-8d80-fea3931a836c"
}
