### POST login (Set access_token to the global variables)
POST {{host}}/api/v0.0.1/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

> {%
    client.test("Request executed successfully", function () {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}


###  CountryController # create
POST {{host}}/api/v0.0.1/countries
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: en

{
  "code": "BG",
  "isoAlpha3": "BGR",
  "continent": "EU",
  "currencyCode": "BGN",
  "name": "Bulgaria",
  "capital": "Sofia",
  "continentName": "Europe",
  "description": "Bulgarian Description",
  "enabled": true
}


###  CountryController # update
PUT {{host}}/api/v0.0.1/countries/BG
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

{
  "code": "BG",
  "isoAlpha3": "BGR",
  "continent": "EU",
  "currencyCode": "BGN",
  "name": "България",
  "capital": "София",
  "continentName": "Европа",
  "description": "Българско описание на България",
  "enabled": true
}


###  CountryController # findAll
GET {{host}}/api/v0.0.1/countries/findAll
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  CountryController # findAllEuMembers
GET {{host}}/api/v0.0.1/countries/eu-members
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  CountryController # findByCode
GET {{host}}/api/v0.0.1/countries/BG
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: en


###  CountryController # search
GET {{host}}/api/v0.0.1/countries/search?q=Бъл
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  CountryController # search
GET {{host}}/api/v0.0.1/countries/search?q=фра&page=0&size=3&sort=i18n.name,ASC
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg


###  CountryController # search
GET {{host}}/api/v0.0.1/countries/search?q=Ber&page=0&size=3&sort=i18n.name,DESC
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: en