### POST login (Set access_token to the global variables)
POST {{host}}/api/v0.0.1/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}


###  Upload File
PUT {{host}}/api/v0.0.1/files/RentalHolder/1?description="NQMA"&main=true
accept: */*
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="bungalow.png"

< bungalow.png

###  Get File (Resource)
GET {{host}}/api/v0.0.1/files/9c4cd02b-c9bb-4425-94a7-337afa512e28/file
accept: */*
Authorization: Bearer {{access_token}}

###  Get FileDTO by id
GET {{host}}/api/v0.0.1/files/9c4cd02b-c9bb-4425-94a7-337afa512e28
accept: */*
Authorization: Bearer {{access_token}}
Content-Type: application/json

### Delete File by id.
DELETE {{host}}/api/v0.0.1/files/4209d415-2d22-4dc5-8de5-254b1c67759e
accept: */*
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
