### POST login (Set access_token to the global variables)
POST {{host}}/api/v0.0.1/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

> {%
    client.test("Request executed successfully", function() {
        if (response.status === 200) {
            client.global.set("access_token", response.body["token"])
            client.global.set("refresh_token", response.body["refreshToken"])
        }
        client.assert(response.status === 200, "Access is Denied");
    });
%}


###  SettlementController # create
POST {{host}}/api/v0.0.1/settlements
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "code" : "69999",
  "name":"Благоевград",
  "nameLat":"Blagoevgrad",
  "regionCode": "BLG",
  "regionName": "Благоевград",
  "regionNameLat": "Благоевград",
  "municipalityCode": "BLG03",
  "municipalityName": "Благоевград",
  "municipalityNameLat": "Благоевград",
  "settlementType": "CITY",
  "tsb": "SW",
  "enabled": true,
  "countryCode": "FR",
  "subSettlements": [
    {
      "code" : "65666",
      "name":"Петрич",
      "nameLat":"Petrich",
      "regionCode": "BLG",
      "regionName": "Благоевград",
      "regionNameLat": "Благоевград",
      "municipalityCode": "BLG03",
      "municipalityName": "Благоевград",
      "municipalityNameLat": "Благоевград",
      "settlementType": "CITY",
      "tsb": "SW",
      "enabled": true,
      "subSettlements" : [
        {
          "code" : "775777",
          "name":"Ключ",
          "nameLat":"kluch",
          "regionCode": "BLG",
          "regionName": "Благоевград",
          "regionNameLat": "Благоевград",
          "municipalityCode": "BLG03",
          "municipalityName": "Благоевград",
          "municipalityNameLat": "Благоевград",
          "settlementType": "VILLAGE",
          "tsb": "SW",
          "enabled": true,
          "subSettlements" : []
        }
      ]
    }
  ]
}


###  SettlementController # update
PUT {{host}}/api/v0.0.1/settlements/09999
Content-Type: application/json
Authorization: Bearer {{access_token}}

{

  "countryCode": "FR"

}


###  SettlementController # findAllParents
GET {{host}}/api/v0.0.1/settlements/parents
accept: */*
Authorization: Bearer {{access_token}}

###  SettlementController # findByCode
GET {{host}}/api/v0.0.1/settlements/68134
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  SettlementController # findAllByParentCode
GET {{host}}/api/v0.0.1/settlements/04279/sub-settlements
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  SettlementController # findAllRegionSettlements
GET {{host}}/api/v0.0.1/settlements/68134/region-settlements
accept: */*
Authorization: Bearer {{access_token}}

###  SettlementController # findAllMunicipalitySettlements
GET {{host}}/api/v0.0.1/settlements/68134/municipality-settlements
accept: */*
Authorization: Bearer {{access_token}}

###  SettlementController # findAllRegions
GET {{host}}/api/v0.0.1/settlements/regions
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  SettlementController # findAllSettlementMunicipalities
GET {{host}}/api/v0.0.1/settlements/10135/settlement-municipalities
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  SettlementController # findAllSettlementAreas
GET {{host}}/api/v0.0.1/settlements/10135/settlement-areas
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  SettlementController # getInfo
GET {{host}}/api/v0.0.1/settlements/63344/info
accept: */*
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  SettlementController # search
GET {{host}}/api/v0.0.1/settlements/search?q=рилски
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept-Language: bg

###  SettlementController # history
GET {{host}}/api/v0.0.1/settlements/04279
accept: */*
Authorization: Bearer {{access_token}}
